### ISSUE TITLE
PA crashes because of missing check scripts under /root/preupgrade/RHEL6_7

### ISSUE THREAD

**Issue by pirat89** [upgrades-migrations/preupgrade-assistant#361]
```
# preupg --force --skip-common --debug --verbose
Warning: tags: 'check_script, solution' are not allowed in config file /root/preupgrade/RHEL6_7/usrmgmt/ypbind/module.ini.
Allowed tags are content_description, config_file, content_title, author, group_title, applies_to, bugzilla, mode, binary_req, requires.
Warning: tags: 'check_script, solution' are not allowed in config file /root/preupgrade/RHEL6_7/usrmgmt/ReservedIDs/module.ini.
Allowed tags are content_description, config_file, content_title, author, group_title, applies_to, bugzilla, mode, binary_req, requires.
Warning: tags: 'check_script, solution' are not allowed in config file /root/preupgrade/RHEL6_7/usrmgmt/libuser/module.ini.
Allowed tags are content_description, config_file, content_title, author, group_title, applies_to, bugzilla, mode, binary_req, requires.
Warning: tags: 'check_script, solution' are not allowed in config file /root/preupgrade/RHEL6_7/usrmgmt/DangerousRanges/module.ini.
Allowed tags are content_description, config_file, content_title, author, group_title, applies_to, bugzilla, mode, binary_req, requires.
Warning: tags: 'check_script, solution' are not allowed in config file /root/preupgrade/RHEL6_7/usrmgmt/ypserv/service_configs/module.ini.
Allowed tags are content_description, config_file, content_title, author, group_title, applies_to, bugzilla, mode, binary_req, requires.
Warning: tags: 'check_script, solution' are not allowed in config file /root/preupgrade/RHEL6_7/usrmgmt/ypserv/max_uid_gid/module.ini.
Allowed tags are content_description, config_file, content_title, author, group_title, applies_to, bugzilla, mode, binary_req, requires.
Warning: tags: 'check_script, solution' are not allowed in config file /root/preupgrade/RHEL6_7/usrmgmt/ypserv/maps_dbm/module.ini.
Allowed tags are content_description, config_file, content_title, author, group_title, applies_to, bugzilla, mode, binary_req, requires.
Warning: tags: 'check_script, solution' are not allowed in config file /root/preupgrade/RHEL6_7/usrmgmt/ypserv/makefile_config/module.ini.
Allowed tags are content_description, config_file, content_title, author, group_title, applies_to, bugzilla, mode, binary_req, requires.
Warning: tags: 'check_script, solution' are not allowed in config file /root/preupgrade/RHEL6_7/databases/mysql/configuration_changes/module.ini.
Allowed tags are content_description, config_file, content_title, author, group_title, applies_to, bugzilla, mode, binary_req, requires.
Warning: tags: 'check_script, solution' are not allowed in config file /root/preupgrade/RHEL6_7/databases/mysql/data_migration/module.ini.
Allowed tags are content_description, config_file, content_title, author, group_title, applies_to, bugzilla, mode, binary_req, requires.
Warning: tags: 'check_script, solution' are not allowed in config file /root/preupgrade/RHEL6_7/databases/mysql/general_changes/module.ini.
Allowed tags are content_description, config_file, content_title, author, group_title, applies_to, bugzilla, mode, binary_req, requires.
Warning: tags: 'check_script, solution' are not allowed in config file /root/preupgrade/RHEL6_7/databases/postgresql/module.ini.
Allowed tags are content_description, config_file, content_title, author, group_title, applies_to, bugzilla, mode, binary_req, requires.
Warning: tags: 'check_script, solution' are not allowed in config file /root/preupgrade/RHEL6_7/selinux/samba/module.ini.
Allowed tags are content_description, config_file, content_title, author, group_title, applies_to, bugzilla, mode, binary_req, requires.
Traceback (most recent call last):
  File "/usr/bin/preupg", line 20, in main
    return_code = app.run()
  File "/usr/lib/python2.6/site-packages/preupg/application.py", line 752, in run
    retval = self.scan_system()
  File "/usr/lib/python2.6/site-packages/preupg/application.py", line 479, in scan_system
    ret_val = self.prepare_scan_system()
  File "/usr/lib/python2.6/site-packages/preupg/application.py", line 423, in prepare_scan_system
    ret_val = xccdf_compose.generate_xml()
  File "/usr/lib/python2.6/site-packages/preupg/xmlgen/compose.py", line 84, in generate_xml
    self.dst_path, generate_from_ini=generate_from_ini)
  File "/usr/lib/python2.6/site-packages/preupg/xmlgen/compose.py", line 419, in run_compose
    generate_from_ini)
  File "/usr/lib/python2.6/site-packages/preupg/xmlgen/compose.py", line 182, in collect_group_xmls
    generate_from_ini))
  File "/usr/lib/python2.6/site-packages/preupg/xmlgen/compose.py", line 171, in collect_group_xmls
    oscap_group.write_xml()
  File "/usr/lib/python2.6/site-packages/preupg/xmlgen/oscap_group_xml.py", line 91, in write_xml
    self.rule = xml_utils.prepare_sections()
  File "/usr/lib/python2.6/site-packages/preupg/xmlgen/xml_utils.py", line 224, in prepare_sections
    self.create_xml_from_ini(ini_filepath, ini_file_content)
  File "/usr/lib/python2.6/site-packages/preupg/xmlgen/xml_utils.py", line 339, in create_xml_from_ini
    function(ini_content, k)
  File "/usr/lib/python2.6/site-packages/preupg/xmlgen/xml_utils.py", line 251, in fnc_check_script
    self.check_script_modification(key, name)
  File "/usr/lib/python2.6/site-packages/preupg/xmlgen/xml_utils.py", line 183, in check_script_modification
    self.mh.check_scripts(k)
  File "/usr/lib/python2.6/site-packages/preupg/xmlgen/script_utils.py", line 39, in check_scripts
    dir=self.dir_name)
MissingFileInContentError: Error: File /root/preupgrade/RHEL6_7/selinux/samba/check missing in the module directory /root/preupgrade/RHEL6_7/selinux/samba
```

**Comment by pirat89** [comment]
I found that it was just because of trash files in /usr/share/preupgrade/RHEL6_7 which should not be there.
